const types = {
  GET_ITEMS: 'GET_ITEMS',
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  ITEM_FETCHING: 'ITEM_FETCHING',
  ERROR_FETCHING: 'ERROR_FETCHING',
  LOGIN: 'LOGIN',
  REGISTER_USER: 'REGISTER_USER',
  USER_FETCHING: 'USER_FETCHING',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  USER_ERROR_FETCHING: 'USER_ERROR_FETCHING',
  LOG_OUT: 'LOG_OUT',
  LOAD_USER: 'LOAD_USER',
  USER_LOADED: 'USER_LOADED',
  ADD_TO_CART: 'ADD_TO_CART',
  GET_USER_CART: 'GET_USER_CART',
  CART_LOADED: 'CART_LOADED',
  CART_ERROR: 'CART_ERROR',
  CART_FETCHING: 'CART_FETCHING',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  RESET_CART_STATE: 'RESET_CART_STATE',

}

export default types
