name: Workflow to run jest unit tests

on: 
  push:
      branches:
          - main

jobs:
  test:
    name: Running unit tests
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
